### ISSUE TITLE
The app is not working

### ISSUE THREAD

**Issue by kannangce** [mschwager/docker-simplesamlphp#1]
I tried the exact steps mentioned in the Readme. After the service is being started, tried hitting http://localhost/simplesaml/index.php and got the below errror.

> SimpleSAML\Error\CriticalConfigurationError: The configuration is invalid: The configuration (config/config.php) is invalid: Missing configuration file
> 
> Backtrace:
> 1 www/_include.php:98 (require_once)
> 0 www/index.php:3 (N/A)

**Comment by mschwager** [comment]
Are you sure you ran `bootstrap.sh`? Without running that script I get the same error.

This script creates a `.storage` directory in the repository that allows you to edit configuration, metadata, and certificates within the containers.

**Comment by scruffycoderofficial** [comment]
@mschwager Which configurations are these you're talking about? Are you perhaps referring to SimpleSAMLPHP Docs?

I am just confused between which one goes first between `./bootstrap.sh` command versus `docker-compose build` or even `docker-compose up`.

Must these files be created before any of the actions above get performed?

@kannangce ever gotten passed this point?

**Comment by mschwager** [comment]
> @mschwager Which configurations are these you're talking about? Are you perhaps referring to SimpleSAMLPHP Docs?

The bootstrap script creates a local directory that contains configuration templates, metadata templates, and a directory for certificates. These correspond to the `config`, `metadata`, and `cert` directories - this should be familiar from the [SimpleSAMLphp install procedure](https://simplesamlphp.org/docs/stable/simplesamlphp-install). This is done so that we can mount these directories to the Docker container and edit the files locally while it is running and/or have the changes persist across container runs. The bootstrap script pre-populates the local directory with the relevant configuration templates. Without this we would mount an empty directory for the Docker volume and SimpleSAMLphp will fail to run without any configuration! I suspect that is what's happening with the "Missing configuration file" error.

> I am just confused between which one goes first between `./bootstrap.sh` command versus `docker-compose build` or even `docker-compose up`.

The order should be: `docker-compose build` -> `./bootstrap.sh` -> `docker-compose up`.

`docker-compose build` builds the Docker images necessary to run SimpleSAMLphp. `bootstrap.sh` creates the relevant local directories as mentioned above. And `docker-compose up` runs the Docker images with the relevant local directories created by the bootstrap script.

> Must these files be created before any of the actions above get performed?

The way this repository and Docker Compose file is structured, yes the files must be created first. If you don't need to edit the configuration locally, or have it persist across container runs, then you could remove the `.storage` volumes from the Compose file and skip the bootstrap step and I believe it should work, but I haven't tested this.

Hope this helps!

**Comment by scruffycoderofficial** [comment]
@mschwager Thanks for the detailed explanation. I could get this project to run successfully after I added my comment. 

Great work you have done here thank you so much for this project.

**Comment by mschwager** [comment]
Great! Glad you got it working and found this helpful!

I'm going to close this out since I think the original issue has been covered :+1:
