### ISSUE TITLE
Seems no longer works?

### ISSUE THREAD

**Issue by venkateshakarle** [mschwager/docker-simplesamlphp#2]
Tried with README options provided.

getting below :

SimpleSAML\Error\CriticalConfigurationError: The configuration is invalid: The configuration (config/config.php) is invalid: Missing configuration file

Backtrace:
1 www/_include.php:98 (require_once)
0 www/index.php:3 (N/A)

seems its not upto date anymore?

**Comment by mschwager** [comment]
Did you run the `bootstrap.sh` script? Per https://github.com/mschwager/docker-simplesamlphp#installing

But yes, this project is old and may not be up-to-date anymore. Versions are pinned and checksums are checked, so I would expect things to still work, but something may have changed in all these years. I would treat this repository as more of an example or reference to get you started rather than a complete base point.

**Comment by mschwager** [comment]
I've just updated this project to the latest version of simplesamlphp and confirmed it's working according to the instructions in the README :+1:
